Basic server-api functionality
vladrus13/productive-programming-tracker pull request #9
Opened 2023-04-25 11:31 UTC by alexanderlvarfolomeev

2023-04-26 17:22 UTC, tarasska commented on server-api/src/main/kotlin/model/Event.kt
> +    companion object {
Вытаскивать общение из БД в статические методы data класса выглядит не самым поддерживаем образом. По крайне мере к следующей проверке я бы предложил вынести работу с БД в какой-нибудь общий GenericDao, а для общности вынеси бы интерфейс всех DB сущностей с методами вида toEntity/fromEntity

2023-04-27 11:22 UTC, vladrus13 requested changes

2023-04-27 11:22 UTC, vladrus13 commented on server-api/src/main/kotlin/dao/DatabaseFactory.kt
> +        ) //throws IOExc
Добавить человекочитаемую обработку ошибок

2023-04-27 11:22 UTC, vladrus13 commented on server-api/src/main/kotlin/dao/DatabaseFactory.kt
> +        val jdbcURL = properties.getProperty("url")!!
Добавить человекочитаемую обработку ошибок

2023-04-27 11:22 UTC, vladrus13 commented on server-api/src/main/kotlin/routing/Routing.kt
> +                val id = call.parameters["id"]?.toLong() ?: return@get call.respondText(
Будет весьма неожиданным получить в ответ на запрос не json, а текст. Можно будет вернуть что то типа
{"result": "Bad request"}

2023-04-27 11:23 UTC, vladrus13 commented on server-api/src/main/kotlin/routing/Routing.kt
> +                val id = call.parameters["id"]?.toLong() ?: return@get call.respondText(
Только этот комментарий является грубым, подлежащим исправлению. Остальные можно будет исправить позже (тем более, на них стоит TODO)

2023-04-27 12:17 UTC, vladrus13 approved these changes

2023-04-27 12:24 UTC, tarasska approved these changes

2023-04-27 12:41 UTC, merged